# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x04main\"\x1e\n\x0eProcessRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xe5\x01\n\x08Response\x12*\n\x04\x43ode\x18\x01 \x01(\x0e\x32\x1c.main.Response.ResponseCodes\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x03 \x01(\x0c\"\x8d\x01\n\rResponseCodes\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x08\n\x04INFO\x10\x03\x12\x08\n\x04NULL\x10\x04\x12\r\n\tNOT_FOUND\x10\x05\x12\x0c\n\x08REQUIRED\x10\x06\x12\x10\n\x0cUNSUFFICIENT\x10\x07\x12\x14\n\x10\x43ONNECTION_ERROR\x10\x08\"3\n\x0fProcessResponse\x12 \n\x08Response\x18\x01 \x01(\x0b\x32\x0e.main.Response2@\n\x04Main\x12\x38\n\x07Process\x12\x14.main.ProcessRequest\x1a\x15.main.ProcessResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSREQUEST._serialized_start=20
  _PROCESSREQUEST._serialized_end=50
  _RESPONSE._serialized_start=53
  _RESPONSE._serialized_end=282
  _RESPONSE_RESPONSECODES._serialized_start=141
  _RESPONSE_RESPONSECODES._serialized_end=282
  _PROCESSRESPONSE._serialized_start=284
  _PROCESSRESPONSE._serialized_end=335
  _MAIN._serialized_start=337
  _MAIN._serialized_end=401
# @@protoc_insertion_point(module_scope)
